name: cuzdan
description: Wallet Application Project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.9
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.4
  google_sign_in: ^5.2.4
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  toggle_switch: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/icons/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
flutter_native_splash:
  background_image: "assets/images/splash.png"
  background_image_dark: "assets/images/splash.png"
